### ISSUE TITLE
on 1.18.2 you need to add the visibility of the hand offset setting

### ISSUE THREAD

**Issue by VaSiLtRoN** [yynaa/TransformHandlers#1]
It is not at all convenient to adjust the offset of the hands. Going out to watch and then back in to set up is not at all convenient

**Comment by yynaa** [comment]
i don't think i'm going to maintain current 1.18.2 and instead export the new alpha to older versions?
and yes, as far as i'm aware, the config gui i use doesn't allow transparent backgrounds, apologies.
